# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  # database: pingpong_elo_board_development
  host: <%= Rails.application.credentials.dig(:development, :database, :host) %>
  port: <%= Rails.application.credentials.dig(:development, :database, :port) %>
  database: <%= Rails.application.credentials.dig(:development, :database, :database) %>
  username: <%= Rails.application.credentials.dig(:development, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>

test:
  <<: *default
  host: <%= Rails.application.credentials.dig(:test, :database, :host) %>
  port: <%= Rails.application.credentials.dig(:test, :database, :port) %>
  database: <%= Rails.application.credentials.dig(:test, :database, :database) %>
  username: <%= Rails.application.credentials.dig(:test, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:test, :database, :password) %>

production:
  primary: &primary_production
    <<: *default
    host: <%= Rails.application.credentials.dig(:production, :database, :host) %> 
    port: <%= Rails.application.credentials.dig(:production, :database, :port) %>
    database: <%= Rails.application.credentials.dig(:production, :database, :database) %>
    username: <%= Rails.application.credentials.dig(:production, :database, :username) %>
    password: <%= Rails.application.credentials.dig(:production, :database, :password) %>
  cache:
    <<: *primary_production
    database: pingpong_elo_board_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: pingpong_elo_board_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: pingpong_elo_board_production_cable
    migrations_paths: db/cable_migrate
